version: '2'

services:
    bot:
      container_name: telegram_bot
      build:
        context: .
      command: python -m bot
      restart: unless-stopped
      env_file:
        - ".env"
      networks:
        - default
      depends_on:
        - postgres
      volumes:
       - ./logs:/src/logs

    postgres:
        container_name: postgres_db
        image: postgres:15
        expose:
          - ${DB_PORT}
        ports:
          - ${DB_PORT}:5432
        networks:
          - default
        environment:
          POSTGRES_HOST: ${DB_HOST}
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge